### ISSUE TITLE
Pegelonline  nit work

### ISSUE THREAD

**Issue by MikeLehnitz** [mattsches/homeassistant-pegelonline#1]
Bei der Installation bekomme ich folgende Meldung: Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble.

**Comment by moppsgti** [comment]
ich bekomme die gleiche Fehlermeldung

**Comment by mattsches** [comment]
Danke für den Hinweis, ich werde mich so bald wie möglich drum kümmern - kann aber noch ein paar Tage dauern. Welche Home Assistant-Version ist denn betroffen?

**Comment by MikeLehnitz** [comment]
Version Hacs Installation OK, Installation Geräte/Dienste ,Integration kommt der Fehler.   HA 2023.4.4 / auf RasP4

**Comment by moppsgti** [comment]
Home Assistant 2023.3.1 Frontend 20230302.0 - latest

**Comment by mattsches** [comment]
Ich habe es gerade in einem frischen Development Setup getestet und konnte den Fehler nicht nachstellen :thinking: 

Allerdings habe ich ein paar Warnings bekommen, für die ich gerade einen Fix gepusht habe - möglicherweise hilft das. Ansonsten muss ich nochmal gucken, wenn ich etwas mehr Zeit habe.

Edit/Update: Auch auf meiner Produktiv-Instanz hat alles geklappt mit dem Release 0.1.1.

**Comment by MikeLehnitz** [comment]
Hallo, Danke für die schnelle Arbeit. Der Fehler ist behoben und die Installation lief Tadellos.

**Comment by mattsches** [comment]
Sehr gut! Nochmals danke fürs Melden, ich schließe das Issue jetzt. Sollte die Meldung wieder auftauchen, bitte gern noch einmal kommentieren.

Möglicherweise lag das Problem am PEGELONLINE API, das vielleicht kurzzeitig nicht verfügbar war. Ich werde bei Gelegenheit versuchen, die Fehlerbehandlung zu verbessern, so dass eine aussagekräftigere Fehlermeldung erscheint.

**Comment by mattsches** [comment]
Sehr gut! Nochmals danke fürs Melden, ich schließe das Issue jetzt. Sollte die Meldung wieder auftauchen, bitte gern noch einmal kommentieren.

Möglicherweise lag das Problem am PEGELONLINE API, das vielleicht kurzzeitig nicht verfügbar war. Ich werde bei Gelegenheit versuchen, die Fehlerbehandlung zu verbessern, so dass eine aussagekräftigere Fehlermeldung erscheint.
